#include<iostream>
#include<fstream>
#include<stdio.h>
#include<string>

usingnamespacestd;

intmain()
{
ifstreamfintrare;
fintrare.open("ex2in.txt");
stringlinie,cautat;
cout<<"Introduceticuvantulpecarevretisailcautati:";
cin>>cautat;
if(fintrare.is_open())
{
intcount=0;
while(!fintrare.eof())
{
getline(fintrare,linie);
for(inti=0;i<=linie.length();i++)
{
intj;
for(j=0;j<cautat.length();j++)
{
if(linie[i+j]!=cautat[j])
{
break;
}
}
if(j==cautat.length())
{
count++;
}
}
}
cout<<"Cuvantul"<<cautat<<"aparede"<<count<<"intextuldat.";
}

fintrare.close();
system("pause");
return0;
}